# Generated by Django 4.2.1 on 2023-05-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(default='0', max_length=10)),
                ('name', models.CharField(default='undef', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_transaction_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('TradeVolume', models.IntegerField()),
                ('HighestPrice', models.FloatField(default=0.0)),
                ('LowestPrice', models.FloatField(default=0.0)),
                ('ClosingPrice', models.FloatField(default=0.0)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.stock_name')),
            ],
        ),
    ]
