<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-05-28 09:04
=======
# Generated by Django 4.2.1 on 2023-05-28 09:08
>>>>>>> 90b3011a885b2e647fa02e50ea2f6ece83b594a4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('mysite', '0001_initial'),
=======
        ("mysite", "0001_initial"),
>>>>>>> 90b3011a885b2e647fa02e50ea2f6ece83b594a4
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='daily_transaction_information',
            name='OpeningPrice',
=======
            model_name="daily_transaction_information",
            name="OpeningPrice",
>>>>>>> 90b3011a885b2e647fa02e50ea2f6ece83b594a4
            field=models.FloatField(default=0.0),
        ),
    ]
