# Generated by Django 4.2 on 2023-05-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='every_day',
            new_name='Daily_transaction_information',
        ),
    ]
