# Generated by Django 4.2.1 on 2023-05-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_transaction_information',
            name='OpeningPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
