# Generated by Django 4.2.1 on 2023-06-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock_profit_rates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_id", models.CharField(default="0", max_length=10)),
                ("name", models.CharField(default="undef", max_length=100)),
                ("profit_rate", models.FloatField(default=0.0)),
            ],
        ),
    ]
