# Generated by Django 4.2.1 on 2023-06-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_stock_profit_rates"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock_profit_rates",
            old_name="profit_rate",
            new_name="bias_profit_rate",
        ),
        migrations.AddField(
            model_name="stock_profit_rates",
            name="kd_profit_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
